workflows:
  # iOS Workflow
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Replace with your bundle ID
        BUNDLE_ID: "com.example.calamityReport"
    
    scripts:
      - name: Set up debug keystore
        script: |
          echo "Setting up iOS project..."
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
          
      - name: Flutter build iOS (Debug - No Signing)
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/ios/iphoneos/*.app
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your.email@example.com  # Replace with your email
        notify:
          success: true
          failure: true

  # Android Workflow (Bonus)
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      flutter: stable
      
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
    publishing:
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true