// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJndUL1MP4KAoadNwTaZdvL8sPt0Tqgw',
    appId: '1:522642764339:web:603214990a762079fe6946',
    messagingSenderId: '522642764339',
    projectId: 'calamity-report',
    authDomain: 'calamity-report.firebaseapp.com',
    storageBucket: 'calamity-report.firebasestorage.app',
    measurementId: 'G-3TKC2KZMQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fO2z8TCrfflfoIdQ8L9UDXlF9RvzFgU',
    appId: '1:522642764339:android:cfa63725b2a4c18dfe6946',
    messagingSenderId: '522642764339',
    projectId: 'calamity-report',
    storageBucket: 'calamity-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtb35mpnYEWsOT2gvFgO5sTZ4fqJ1i1pY',
    appId: '1:522642764339:ios:690d9020d81b1fadfe6946',
    messagingSenderId: '522642764339',
    projectId: 'calamity-report',
    storageBucket: 'calamity-report.firebasestorage.app',
    iosBundleId: 'com.example.calamityReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtb35mpnYEWsOT2gvFgO5sTZ4fqJ1i1pY',
    appId: '1:522642764339:ios:690d9020d81b1fadfe6946',
    messagingSenderId: '522642764339',
    projectId: 'calamity-report',
    storageBucket: 'calamity-report.firebasestorage.app',
    iosBundleId: 'com.example.calamityReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJndUL1MP4KAoadNwTaZdvL8sPt0Tqgw',
    appId: '1:522642764339:web:d74ef4c26eb490edfe6946',
    messagingSenderId: '522642764339',
    projectId: 'calamity-report',
    authDomain: 'calamity-report.firebaseapp.com',
    storageBucket: 'calamity-report.firebasestorage.app',
    measurementId: 'G-ZFC9KYFQCF',
  );

}